jobs:
- deployment: VMDeploy
  displayName: web
  pool:
    vmImage: 'Ubuntu-18.04'
  environment:
    name: 09157-azure-cicd
    resourceType: VirtualMachine
  strategy:
      runOnce:
        deploy:
          steps:
          - script: cp -p index.html /appsrc
